src/main/java/com/cibertec/examenlinea/bean/Curso.java
package com.cibertec.examenlinea.bean;

import java.io.Serializable;
import javax.persistence.*;
import java.util.Date;
import java.util.List;


/**
 * The persistent class for the Curso database table.
 * 
 */
@Entity
@Table(name="Curso")
@NamedQuery(name="Curso.findAll", query="SELECT c FROM Curso c")
public class Curso implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;

	private String descripcion;

	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	private Date fecha;

	private String nombre;

	//bi-directional many-to-one association to Examen
	@OneToMany(mappedBy="curso")
	private List<Examen> examens;

	//bi-directional many-to-one association to Pregunta
	@OneToMany(mappedBy="curso", fetch=FetchType.EAGER)
	private List<Pregunta> preguntas;

	//bi-directional many-to-many association to Usuario
	@ManyToMany(mappedBy="cursos")
	private List<Usuario> usuarios;

	//bi-directional many-to-one association to UsuarioCurso
	@OneToMany(mappedBy="curso")
	private List<UsuarioCurso> usuarioCursos;
	
	public Curso() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(List<Examen> examens) {
		this.examens = examens;
	}

	public Examen addExamen(Examen examen) {
		getExamens().add(examen);
		examen.setCurso(this);

		return examen;
	}

	public Examen removeExamen(Examen examen) {
		getExamens().remove(examen);
		examen.setCurso(null);

		return examen;
	}

	public List<Pregunta> getPreguntas() {
		return this.preguntas;
	}

	public void setPreguntas(List<Pregunta> preguntas) {
		this.preguntas = preguntas;
	}

	public Pregunta addPregunta(Pregunta pregunta) {
		getPreguntas().add(pregunta);
		pregunta.setCurso(this);

		return pregunta;
	}

	public Pregunta removePregunta(Pregunta pregunta) {
		getPreguntas().remove(pregunta);
		pregunta.setCurso(null);

		return pregunta;
	}

	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public List<UsuarioCurso> getUsuarioCursos() {
		return this.usuarioCursos;
	}

	public void setUsuarioCursos(List<UsuarioCurso> usuarioCursos) {
		this.usuarioCursos = usuarioCursos;
	}

	public UsuarioCurso addUsuarioCurso(UsuarioCurso usuarioCurso) {
		getUsuarioCursos().add(usuarioCurso);
		usuarioCurso.setCurso(this);

		return usuarioCurso;
	}

	public UsuarioCurso removeUsuarioCurso(UsuarioCurso usuarioCurso) {
		getUsuarioCursos().remove(usuarioCurso);
		usuarioCurso.setCurso(null);

		return usuarioCurso;
	}

	@Override
	public String toString() {
		return "Curso [id=" + id + ", descripcion=" + descripcion + ", estado=" + estado + ", fecha=" + fecha
				+ ", nombre=" + nombre + ", usuarios=" + usuarios + "]";
	}

}

src/main/java/com/cibertec/examenlinea/bean/Usuario.java
package com.cibertec.examenlinea.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * The persistent class for the Usuario database table.
 * 
 */
@Entity
@Table(name="Usuario")
@NamedQuery(name="Usuario.findAll", query="SELECT u FROM Usuario u")
public class Usuario implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;

	private String apellido;

	private String email;

	private String estado;

	@Temporal(TemporalType.DATE)
	private Date fechaRegistro;

	private String nombre;

	private String password;

	private String rol;

	private String usuario;

	//bi-directional many-to-one association to Resultado
	@OneToMany(mappedBy="usuario")
	private List<Resultado> resultados;

	//bi-directional many-to-many association to Curso
	@ManyToMany
	@JoinTable(
		name="UsuarioCurso"
		, joinColumns={
			@JoinColumn(name="idUsuario")
			}
		, inverseJoinColumns={
			@JoinColumn(name="idCurso")
			}
		)
	private List<Curso> cursos;

	//bi-directional many-to-one association to UsuarioCurso
	@OneToMany(mappedBy="usuario")
	private List<UsuarioCurso> usuarioCursos;

	public Usuario() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public List<Resultado> getResultados() {
		return this.resultados;
	}

	public void setResultados(List<Resultado> resultados) {
		this.resultados = resultados;
	}

	public Resultado addResultado(Resultado resultado) {
		getResultados().add(resultado);
		resultado.setUsuario(this);

		return resultado;
	}

	public Resultado removeResultado(Resultado resultado) {
		getResultados().remove(resultado);
		resultado.setUsuario(null);

		return resultado;
	}

	public List<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(List<Curso> cursos) {
		this.cursos = cursos;
	}

	public List<UsuarioCurso> getUsuarioCursos() {
		return this.usuarioCursos;
	}

	public void setUsuarioCursos(List<UsuarioCurso> usuarioCursos) {
		this.usuarioCursos = usuarioCursos;
	}

	public UsuarioCurso addUsuarioCurso(UsuarioCurso usuarioCurso) {
		getUsuarioCursos().add(usuarioCurso);
		usuarioCurso.setUsuario(this);

		return usuarioCurso;
	}

	public UsuarioCurso removeUsuarioCurso(UsuarioCurso usuarioCurso) {
		getUsuarioCursos().remove(usuarioCurso);
		usuarioCurso.setUsuario(null);

		return usuarioCurso;
	}
	
	public Date getCurrentDate() {
		return new Date();
	}

}

src/main/java/com/cibertec/examenlinea/controller/CursoController.java
package com.cibertec.examenlinea.controller;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.primefaces.component.api.UIData;
import org.primefaces.context.RequestContext;

import com.cibertec.examenlinea.bean.Curso;
import com.cibertec.examenlinea.bean.Examen;
import com.cibertec.examenlinea.service.CursoService;
import com.cibertec.examenlinea.service.ExamenService;

@RequestScoped
@ManagedBean(name = "cursoController")
public class CursoController {
	
	private CursoService cursoService = new CursoService();
	private ExamenService examenService = new ExamenService();
	private Curso curso;
	private List<Curso> cursos;
	// Permite obtener el elemento selecionado del datatable del mantenimiento
	
	private UIData dttCursos;
	private int cursoId;
	private Examen examen;
	
	@PostConstruct
	public void init() {
		curso = new Curso();
		cursos = cursoService.listar();
	}

	public String registrar() {
		String redirect = null;
		try {
			curso.setEstado("0");
			curso = cursoService.registrar(curso);
			FacesContext context = FacesContext.getCurrentInstance();
			context.getExternalContext().getFlash().setKeepMessages(true);
			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Aviso", 
							"Se registro satisfactioramente."));
			redirect = "/pages/admin/curso/editar?faces-redirect=true&cursoId=" + curso.getId();
		} catch (Exception e) {
			FacesContext.getCurrentInstance()
			.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Aviso", "Error al grabar los datos"));
		}
		return redirect;
	}
	
	public String editar() {
		// getRowData(); --> Obtiene el objeto seleccionado
		curso = (Curso) dttCursos.getRowData();
		return "/pages/admin/curso/editar"; 
	}
	
	public String actualizar() {
		String redirect = null;
		try {
			curso = cursoService.actualizar(curso);

			FacesContext context = FacesContext.getCurrentInstance();
			context.getExternalContext().getFlash().setKeepMessages(true);
			context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Aviso", 
							"Se registro satisfactioramente."));
			redirect = "/pages/admin/curso/editar?faces-redirect=true&cursoId=" + curso.getId();
		} catch (Exception e) {
			FacesContext.getCurrentInstance()
			.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Aviso", "Error al grabar los datos"));
		}
		return redirect;
	}
	
	public void dialogCurso(int idCurso, String estado) {
		this.curso = cursoService.obtener(idCurso);
		RequestContext req = RequestContext.getCurrentInstance();
		req.execute("PF('" + (estado.equals("0") ? "wdlgActivarCurso" : "wdlgDesactivarCurso") + "').show();");
	}

	public void activarCurso() {
		try {
			curso = cursoService.obtener(curso.getId());
			curso.setEstado("1");
			cursoService.actualizar(curso);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		RequestContext req = RequestContext.getCurrentInstance();
		req.execute("PF('wdlgActivarCurso').hide();");
	}

	public void desactivarCurso() {
		try {
			curso = cursoService.obtener(curso.getId());
			curso.setEstado("0");
			cursoService.actualizar(curso);
		} catch (Exception e) {
			e.printStackTrace();
		}
		RequestContext req = RequestContext.getCurrentInstance();
		req.execute("PF('wdlgDesactivarCurso').hide();");
	}
	
	public Curso getCurso() {
		return curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public List<Curso> getCursos() {
		return cursos;
	}

	public void setCursos(List<Curso> cursos) {
		this.cursos = cursos;
	}	

	public UIData getDttCursos() {
		return dttCursos;
	}

	public void setDttCursos(UIData dttCursos) {
		this.dttCursos = dttCursos;
	}

	public int getCursoId() {
		return cursoId;
	}

	public void setCursoId(int cursoId) {
		this.curso = cursoService.obtener(cursoId);
		this.curso.setExamens(examenService.examenesxcurso(curso.getId()));
		this.cursoId = cursoId;
	}

	public Examen getExamen() {
		return examen;
	}

	public void setExamen(Examen examen) {
		this.examen = examen;
	}

}

src/main/webapp/pages/estudiante/curso/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="../../principal.xhtml">
	<ui:define name="title">Cursos</ui:define>
	<ui:define name="content">
		<h:form>
			<div class="ui grid">
				<div class="ui-grid-row">
					<div class="ui-grid-col-12">
						<h2>Inscribase a un curso</h2>
					</div>
				</div>
			</div>
			<p:dataGrid var="curso" value="#{usuariocursoController.cursos}" columns="3" layout="grid" >
				<p:panel header="#{curso.nombre}" style="text-align:center">
            		<h:panelGrid columns="1" style="width:100%">		 
		                <h:outputText value="#{curso.descripcion}" />
		                <p:link value="Ver curso" outcome="show" >
				    		<f:param name="cursoId" value="#{curso.id}" />
						</p:link>
		            </h:panelGrid>
		        </p:panel>
				
		    </p:dataGrid>
		
		</h:form>
	</ui:define>
</ui:composition>
</html>

src/main/webapp/pages/estudiante/curso/show.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<f:metadata>
    <f:viewParam name="cursoId" value="#{usuariocursoController.cursoId}" />
</f:metadata>

<ui:composition template="../../principal.xhtml">
	<ui:define name="title">Cursos</ui:define>
	<ui:define name="content">
		<h:form style="text-align:center;">
			<div class="ui grid">
				<div class="ui-grid-row" style="margin-bottom:1em;">
					<div class="ui-grid-col-12">
						<h1>#{usuariocursoController.curso.nombre}</h1>
						<p:outputLabel value="#{usuariocursoController.curso.descripcion}" />	
					</div>
				</div>
				<div class="ui-grid-row" style="margin-bottom:1em;">
					<div class="ui-grid-col-12">
						<p:outputLabel value="Fecha creación: " />							
						<h:outputText value="#{usuariocursoController.curso.fecha}" >
							<f:convertDateTime pattern="dd/MM/yyyy" />
						</h:outputText>
					</div>
				</div>
				<h:panelGroup styleClass="ui-grid-row"  
							  style="display:block;margin-bottom:1em" 
							  rendered="#{usuariocursoController.usuario_yatiene_curso}">
					<p:outputLabel value="Termine los examenes." />
				</h:panelGroup>
				<h:panelGroup styleClass="ui-grid-row"  
							  style="display:block;margin-bottom:1em" 
							  rendered="#{!usuariocursoController.usuario_yatiene_curso}">
					<div class="ui-grid-col-12">
						<p:commandButton value="Agregar a mis cursos" 
										 action="#{usuariocursoController.agregarMisCursos}"/>
					</div>
				</h:panelGroup>
				<div class="ui-grid-row" style="padding-left:30%;">
					<div class="ui-grid-col-12" style="width:60%;">
						<p:dataList value="#{usuariocursoController.curso.examens}" var="examen" type="ordered"
									rowIndexVar="ii">
					        <f:facet name="header">
					            Examenes por aprobar: 
					        </f:facet>
					        #{examen.nombre}
					        
					        <p:link value="Comenzar" 
					        		rendered="#{usuariocursoController.usuario_yatiene_curso and empty usuariocursoController.resultados[ii] and (usuariocursoController.usuario.currentDate ge examen.fechaInicio and usuariocursoController.usuario.currentDate le examen.fechaFin)}" 
					        		outcome="examen/comenzar" >
				    			<f:param name="examenId" value="#{examen.id}" />
				    		</p:link>
					        <p:link value="Ver resultado" 
					        		rendered="#{usuariocursoController.usuario_yatiene_curso and not empty usuariocursoController.resultados[ii]}" 
					        		outcome="resultado/show" >
				    			<f:param name="resultadoId" value="#{usuariocursoController.resultados[ii].id}" />
				    		</p:link>
					    </p:dataList>
					</div>
				</div>
			</div>
			
		</h:form>
	</ui:define>
</ui:composition>
</html>